### ISSUE TITLE
[Enhancement] Provide the ability to manually edit the ribbons assigned to Kerbals

### ISSUE THREAD

**Issue by ferguscollins** [Nereid42/FinalFrontier#12]
I have the mod installed through CKAN and it uninstalled after a minor game update, so now some of the firsts and logs are incorrect. I tried editing the `/GameData/FinalFrontier.dat` file manually but it is not stored in plain text.

**Comment by Nereid42** [comment]
The achievements/ribbons are stored in the save game and not in the FinalFrontier.dat.

 
 

Gesendet: Freitag, 17. Juli 2020 um 17:37 Uhr
Von: "Fergus Collins" <notifications@github.com>
An: "Nereid42/FinalFrontier" <FinalFrontier@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [Nereid42/FinalFrontier] [Enhancement] Provide the ability to manually edit the ribbons assigned to Kerbals (#12)


 

I have the mod installed through CKAN and it uninstalled after a minor game update, so now some of the firsts and logs are incorrect. I tried editing the /GameData/FinalFrontier.dat file manually but it is not stored in plain text.

**Comment by ferguscollins** [comment]
Ah thank you, I'll close the issue. Great mod! I love statistics.
