### ISSUE TITLE
Possible bug with the mod

### ISSUE THREAD

**Issue by Will-Nichols** [Nereid42/FinalFrontier#13]
So I just reloaded Final Frontier after not having played KSP in about a year. When I reloaded it I would get an error being reported that another mod (Tweakscale) was showing errors. When I opened the log file this is what was found...
`Uploading Crash Report
TypeLoadException: Could not load type of field 'Nereid.FinalFrontier.EventObserver:lastVesselSurfacePosition' (7) due to: Could not load file or assembly 'KSPUtil, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:KSP
Util, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>

Rethrow as TypeInitializationException: The type initializer for 'Nereid.FinalFrontier.FinalFrontier' threw an exception.`

After messing around with it for a day or so the only solution to eliminating this bug has been to remove Final Frontier from my mods that I launch the game with. Once I do that the game plays as it should. I would really like to be able to help with this but not sure where to start.

Links are here for the two log files; [KSP.log](https://drive.google.com/file/d/1eszIK8xE6YBS9naxIn8_BCeLCDsDAVoF/view?usp=sharing) and [player.log](https://drive.google.com/file/d/19VuSC8exwK5xhJilh0h0MG8ogRDPWCw8/view?usp=sharing).

**Comment by linuxgurugamer** [comment]
You should close this, since according to the forum thread, it was a bad install of two OTHER older mods

**Comment by Will-Nichols** [comment]
Updated results with the changes in the forum post.
[https://forum.kerbalspaceprogram.com/index.php?/topic/61065-1100-final-frontier-kerbal-individual-merits-1100-3485/&do=findComment&comment=4104894](url)

Restarted the game and it is loading correctly.
