### ISSUE TITLE
Latest version unavailable

### ISSUE THREAD

**Issue by shibdib** [Nereid42/FinalFrontier#2]
Kerbalstuff is down and this github is outdated :(

**Comment by Nereid42** [comment]
Hi!

Thanks for your info. I'm a bit busy at the moment but I will upload an  
updated version on curse tomorrow.

Regards,
   André

> Kerbalstuff is down and this github is outdated :(
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Nereid42/FinalFrontier/issues/2

## 

Using Opera's revolutionary e-mail client: http://www.opera.com/mail/

---

Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by shibdib** [comment]
Can't wait, don't want to start a new game without the addon installed :P

**Comment by Nereid42** [comment]
available on spacedock. closed
