### ISSUE TITLE
Keybind for FinalFrontier same as default keybind for Kerbal climb.

### ISSUE THREAD

**Issue by QuickBASIC** [Nereid42/FinalFrontier#3]
Maybe I'm mistaken, but I can't seem to find where in the config it can be changed.

**Comment by Nereid42** [comment]
It cannot. You can only disable it.

> Maybe I'm mistaken, but I can't seem to find where in the config it can  
> be changed.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Nereid42/FinalFrontier/issues/3

## 

Using Opera's revolutionary e-mail client: http://www.opera.com/mail/

---

Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by QuickBASIC** [comment]
Is there any reason the keybind couldn't be set to something else that doesn't conflict with the default keybinds?

**Comment by Nereid42** [comment]
Yes.

a) it shouldn't conflict (Alt-F instead of F)
b) Its just a workaround for those without Blizzys toolbar; maybe I will remove it, because the stock toolbar works fine.

**Comment by Nereid42** [comment]
keybind now configurable. closed
